### ISSUE TITLE
Does spmoran wok for the polygon data of sf format?

### ISSUE THREAD

**Issue by zhenchun** [dmuraka/spmoran#2]
I saw the code ot ```meigen``` works with coordinates of points. Just wondering, does this function allow polygon of sf format?

Thanks a lot!

**Comment by dmuraka** [comment]
Yes. When using sf polygon data, you need to make a proximity matrix first. Here is a sample code:

library(CARBayesdata); library(spmoran)
data("pollutionhealthdata")
dat2007<-pollutionhealthdata[pollutionhealthdata$year==2007,]
dat2007[1:4, ]    # IZ = zone ID

#### Make proximity matrix from sf polygon
data("GGHB.IZ") # GGHB.IZ is a polygon data in sf format
GGHB.IZ[1:4,]     # IZ =zone ID
W.nb   <- poly2nb(GGHB.IZ)
W.list  <- nb2listw(W.nb, style = "B")
W       <- nb2mat(W.nb, style = "B")

#### For spatial data
y       <- log(dat2007[,"observed"])
x       <- dat2007[,c("jsa","price","pm10")]
meig <- meigen( cmat=W )
mod1<- resf(y=y, x=x, meig=meig)

#### For panel data
dat    <- pollutionhealthdata
y       <- log(dat[,"observed"])
x       <- dat[,c("jsa","price","pm10")]
s_id   <- dat[,"IZ"]
meig <- meigen( cmat=W, s_id=s_id )
mod2<- resf(y=y, x=x, meig=meig)

**Comment by zhenchun** [comment]
Thanks a lot!
