### ISSUE TITLE
undeclared spData revision breaks spmoran

### ISSUE THREAD

**Issue by rsbivand** [dmuraka/spmoran#4]
@dmuraka In weigen.Rd, you use the `boston_tracts` data set. `spData` is switching from ESRI Shapefile to GeoPackage, see https://github.com/Nowosad/spData/issues/62. You also did not declare `spData`, so we missed `spmoran` in earlier reverse dependency checks, hence the need for action now, as `spData` will be submitted to CRAN soon. I edited the two affected files: 
[spData_changes.zip](https://github.com/user-attachments/files/17979309/spData_changes.zip) and have checked the package with the forthcoming version of `spData`, which you may also try from for example https://nowosad.r-universe.dev/spData.

**Comment by dmuraka** [comment]
Thank you very much! spmoran version 0.3.2, which replaces the affected files, is subbmited on CRAN. It will be available soon.
